TRUNCATE TABLE account RESTART IDENTITY;
TRUNCATE TABLE address RESTART IDENTITY;
TRUNCATE TABLE certification RESTART IDENTITY;
TRUNCATE TABLE company RESTART IDENTITY;
TRUNCATE TABLE company_document RESTART IDENTITY;
TRUNCATE TABLE company_member RESTART IDENTITY;
TRUNCATE TABLE company_operation RESTART IDENTITY;
TRUNCATE TABLE evidence_item RESTART IDENTITY;
TRUNCATE TABLE guarantee RESTART IDENTITY;
TRUNCATE TABLE invitation RESTART IDENTITY;
TRUNCATE TABLE market RESTART IDENTITY;
TRUNCATE TABLE note RESTART IDENTITY;
TRUNCATE TABLE notification RESTART IDENTITY;
TRUNCATE TABLE product RESTART IDENTITY;
TRUNCATE TABLE project RESTART IDENTITY;
TRUNCATE TABLE project_member RESTART IDENTITY;
TRUNCATE TABLE system RESTART IDENTITY;
TRUNCATE TABLE system_member RESTART IDENTITY;

SELECT SETVAL('account_id_seq', (select MAX(ID) from account));
SELECT SETVAL('address_id_seq', (select MAX(ID) from address));
SELECT SETVAL('certification_id_seq', (select MAX(ID) from certification));
SELECT SETVAL('company_id_seq', (select MAX(ID) from company)); 
        SELECT SETVAL('company_reference_number_seq', (select MAX(reference_number) from company));
SELECT SETVAL('company_document_id_seq', (select MAX(ID) from company_document));
SELECT SETVAL('company_member_id_seq', (select MAX(ID) from company_member));
SELECT SETVAL('company_operation_id_seq', (select MAX(ID) from company_operation));
SELECT SETVAL('evidence_item_id_seq', (select MAX(ID) from evidence_item));
SELECT SETVAL('guarantee_id_seq', (select MAX(ID) from guarantee));
SELECT SETVAL('invitation_id_seq', (select MAX(ID) from invitation));
SELECT SETVAL('market_id_seq', (select MAX(ID) from market));
SELECT SETVAL('note_id_seq', (select MAX(ID) from note));
SELECT SETVAL('notification_id_seq', (select MAX(ID) from notification));
SELECT SETVAL('product_id_seq', (select MAX(ID) from product));
SELECT SETVAL('project_id_seq', (select MAX(ID) from project));
SELECT SETVAL('project_member_id_seq', (select MAX(ID) from project_member));
SELECT SETVAL('system_id_seq', (select MAX(ID) from system));
SELECT SETVAL('system_member_id_seq', (select MAX(ID) from system_member));
