export const microCopy = {
  ROOF_SELECTION_TITLE: "roofSelection.title",
  ROOF_SELECTION_SUBTITLE: "roofSelection.subtitle",
  ROOF_SELECTION_GABLE: "roofSelection.gable",
  ROOF_SELECTION_HIPPED: "roofSelection.hipped",
  ROOF_SELECTION_SLOPED: "roofSelection.sloped",
  ROOF_SELECTION_ROOF: "roofSelection.roof",
  ROOF_DIMENSIONS_TITLE: "roofDimensions.title",
  ROOF_DIMENSIONS_SUBTITLE: "roofDimensions.subtitle",
  ROOF_DIMENSIONS_NEXT_LABEL: "roofDimensions.nextLabel",
  ROOF_DIMENSIONS_BACK_LABEL: "roofDimensions.backLabel",
  ROOF_DIMENSIONS_PROTRUSIONS_TITLE: "roofDimensions.protrusions.title",
  ROOF_DIMENSIONS_PROTRUSIONS_ADD: "roofDimensions.protrusions.add",
  ROOF_DIMENSIONS_PROTRUSIONS_PROMPT: "roofDimensions.protrusions.prompt",
  ROOF_DIMENSIONS_PROTRUSIONS_ADD_ANOTHER:
    "roofDimensions.protrusions.addAnother",
  ROOF_DIMENSIONS_PROTRUSIONS_REMOVE: "roofDimensions.protrusions.remove",
  TILE_SELECTION_TITLE: "tileSelection.title",
  TILE_SELECTION_SUBTITLE: "tileSelection.subtitle",
  TILE_SELECTION_BACK_LABEL: "tileSelection.backLabel",
  TILE_SELECTION_CATEGORIES_CONCRETE: "tileSelection.categories.concrete",
  TILE_SELECTION_CATEGORIES_CLAY: "tileSelection.categories.clay",
  TILE_SELECTION_CATEGORIES_METAL: "tileSelection.categories.metal",
  TILE_SELECTION_COLOR: "tileSelection.color",
  TILE_SELECTION_COLORS: "tileSelection.colors",
  TILE_SELECTION_EMPTY: "tileSelection.empty",
  VARIANT_SELECTION_TITLE: "variantSelection.title",
  VARIANT_SELECTION_SUBTITLE: "variantSelection.subtitle",
  VARIANT_SELECTION_BACK_LABEL: "variantSelection.backLabel",
  TILE_OPTIONS_TITLE: "tileOptions.title",
  TILE_OPTIONS_SUBTITLE: "tileOptions.subtitle",
  TILE_OPTIONS_NEXT_LABEL: "tileOptions.nextLabel",
  TILE_OPTIONS_BACK_LABEL: "tileOptions.backLabel",
  TILE_OPTIONS_VERGE_TITLE: "tileOptions.verge.title",
  TILE_OPTIONS_VERGE_HELP: "tileOptions.verge.help",
  TILE_OPTIONS_VERGE_NONE_LABEL: "tileOptions.verge.noneLabel",
  TILE_OPTIONS_RIDGE_TITLE: "tileOptions.ridge.title",
  TILE_OPTIONS_RIDGE_HELP: "tileOptions.ridge.help",
  TILE_OPTIONS_VENTILATION_HOOD_TITLE: "tileOptions.ventilationHood.title",
  TILE_OPTIONS_VENTILATION_HOOD_HELP: "tileOptions.ventilationHood.help",
  TILE_OPTIONS_VENTILATION_HOOD_NONE_LABEL:
    "tileOptions.ventilationHood.noneLabel",
  UNDERLAY_SELECTION_TITLE: "underlaySelection.title",
  UNDERLAY_SELECTION_SUBTITLE: "underlaySelection.subtitle",
  UNDERLAY_SELECTION_NEXT_LABEL: "underlaySelection.nextLabel",
  UNDERLAY_SELECTION_BACK_LABEL: "underlaySelection.backLabel",
  UNDERLAY_SELECTION_EMPTY: "underlaySelection.empty",
  GUTTERING_TITLE: "guttering.title",
  GUTTERING_SUBTITLE: "guttering.subtitle",
  GUTTERING_NEXT_LABEL: "guttering.nextLabel",
  GUTTERING_BACK_LABEL: "guttering.backLabel",
  GUTTERING_SKIP_LABEL: "guttering.skipLabel",
  GUTTERING_GUTTER_TITLE: "guttering.gutter.title",
  GUTTERING_GUTTER_VARIANT_TITLE: "guttering.gutterVariant.title",
  GUTTERING_GUTTER_HOOK_TITLE: "guttering.gutterHook.title",
  GUTTERING_DOWN_PIPE_TITLE: "guttering.downPipe.title",
  GUTTERING_DOWN_PIPE_CONNECTORS_TITLE: "guttering.downPipeConnectors.title",
  RESULTS_TITLE: "results.title",
  RESULTS_SUBTITLE: "results.subtitle",
  RESULTS_AREA_LABEL: "results.areaLabel",
  RESULTS_BACK_LABEL: "results.backLabel",
  RESULTS_START_OVER_LABEL: "results.startOverLabel",
  RESULTS_DOWNLOAD_PDF_LABEL: "results.downloadPdfLabel",
  RESULTS_CATEGORIES_TITLES: "results.categories.tiles",
  RESULTS_CATEGORIES_FIXINGS: "results.categories.fixings",
  RESULTS_CATEGORIES_SEALING: "results.categories.sealing",
  RESULTS_CATEGORIES_VENTILATION: "results.categories.ventilation",
  RESULTS_CATEGORIES_ACCESSORIES: "results.categories.accessories",
  RESULTS_TABLE_TITLE: "results.table.title",
  RESULTS_TABLE_PACK_SIZE: "results.table.packSize",
  RESULTS_TABLE_EXTERNAL_PRODUCT_CODE: "results.table.externalProductCode",
  RESULTS_TABLE_QUANTITY: "results.table.quantity",
  RESULTS_TABLE_REMOVE: "results.table.remove",
  RESULTS_ALERTS_QUANTITIES_NOT_UPDATED_TITLE:
    "results.alerts.quantities.not.updated.title",
  RESULTS_ALERTS_QUANTITIES_NOT_UPDATED_TEXT:
    "results.alerts.quantities.not.updated.text",
  RESULTS_ALERTS_QUANTITIES_UPDATED_TITLE:
    "results.alerts.quantities.updated.title",
  RESULTS_ALERTS_QUANTITIES_UPDATED_TEXT:
    "results.alerts.quantities.updated.text",
  RESULTS_ALERTS_QUANTITIES_RESET_BUTTON:
    "results.alerts.quantities.reset.button",
  RESULTS_ALERTS_NEED_TO_KNOW_TITLE: "results.alerts.needToKnow.title",
  RESULTS_ALERTS_NEED_TO_KNOW_TEXT: "results.alerts.needToKnow.text",
  RESULTS_EMAIL_TITLE: "results.email.title",
  RESULTS_EMAIL_HELP: "results.email.help",
  RESULTS_EDITED_PRODUCTS_TITLE: "results.edited.products.title",
  PDF_REPORT_EXTRAS_SECTION_TITLE: "pdf.report.extras.section.title",
  VALIDATION_ERRORS_FIELD_REQUIRED: "validation.errors.fieldRequired",
  VALIDATION_ERRORS_POSITIVE_NUMBERS_ONLY:
    "validation.errors.positiveNumberOnly",
  VALIDATION_ERRORS_LENGTH_RANGE: "validation.errors.lengthRange",
  VALIDATION_PITCH_RANGE: "validation.errors.pitchRange",
  CALCULATOR_NOBB_LABEL: "calculator.nobb.label"
};
