process.env.SECRET_MAN_GCP_PROJECT_NAME = "TEST_SECRET_MAN_GCP_PROJECT_NAME";
process.env.CONTENTFUL_MANAGEMENT_TOKEN_SECRET =
  "TEST_CONTENTFUL_MANAGEMENT_TOKEN_SECRET";
process.env.CONTENTFUL_SPACE_ID = "TEST_CONTENTFUL_SPACE_ID";
process.env.CONTENTFUL_ENVIRONMENT = "TEST_CONTENTFUL_ENVIRONMENT";
