const INSTALLER_PERMISSIONS = [];
const COMPANY_ADMIN_PERMISSIONS = [...INSTALLER_PERMISSIONS, "invite"];
const MARKET_ADMIN_PERMISSIONS = [...COMPANY_ADMIN_PERMISSIONS];
const SUPER_ADMIN_PERMISSIONS = [...MARKET_ADMIN_PERMISSIONS];

export default {
  INSTALLER: INSTALLER_PERMISSIONS,
  COMPANY_ADMIN: COMPANY_ADMIN_PERMISSIONS,
  MARKET_ADMIN: MARKET_ADMIN_PERMISSIONS,
  SUPER_ADMIN: SUPER_ADMIN_PERMISSIONS
};
