# re-build
FROM node:14-alpine as build

WORKDIR /usr/src/app


ARG NPM_AUTH_READ_TOKEN
COPY .npmrc .npmrc

COPY ./.yarn ./.yarn
COPY ./.yarnrc ./.yarnrc
COPY yarn.lock .
COPY package.json .

COPY tsconfig.json .
COPY babel.config.js .
COPY .eslintrc.js .
COPY .lintstagedrc.js .
COPY ./@types ./@types

COPY ./applications/intouch/frontend ./applications/intouch/frontend
COPY ./applications/intouch/libraries ./applications/intouch/libraries
COPY ./applications/intouch/api/types ./applications/intouch/api/types

RUN yarn install --pure-lockfile --non-interactive --ignore-optional --cache-folder ./ycache && \
  rm -rf ./ycache

RUN rm -f ./npmrc

WORKDIR /usr/src/app/applications/intouch/frontend

ARG AUTH0_COOKIE_DOMAIN

RUN yarn run build


FROM node:14-alpine

ENV NODE_ENV production

WORKDIR /usr/src/app


ARG NPM_AUTH_READ_TOKEN
COPY .npmrc .npmrc

COPY ./.yarn ./.yarn
COPY ./.yarnrc ./.yarnrc
COPY yarn.lock .
COPY package.json .

COPY tsconfig.json .
COPY babel.config.js .
COPY .eslintrc.js .
COPY .lintstagedrc.js .
COPY ./@types ./@types

COPY ./applications/intouch/frontend ./applications/intouch/frontend
COPY ./applications/intouch/libraries ./applications/intouch/libraries
COPY ./applications/intouch/api/types ./applications/intouch/api/types

COPY --from=build /usr/src/app/applications/intouch/frontend/.next ./applications/intouch/frontend/.next

RUN ls -l && \
  yarn install --pure-lockfile --non-interactive --ignore-optional --production --cache-folder ./ycache && \
  rm -rf ./ycache

RUN rm -f ../../../.npmrc

WORKDIR /usr/src/app/applications/intouch/frontend

EXPOSE 3000

ENV NEXT_TELEMETRY_DISABLED 1

CMD ["yarn", "start"]
