FROM node:12

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Install all Packages
RUN yarn

# Copy all other source code to work directory
ADD . /usr/src/app
# TypeScript
RUN yarn tsc

# Start
CMD [ "yarn", "start" ]
EXPOSE 8080

