export const microCopy = {
  DIALOG_CLOSE: "dialog.close",
  DIALOG_CANCEL: "dialog.cancel",
  DIALOG_CONFIRM: "dialog.confirm",
  DIALOG_RETRY: "dialog.retry",

  GLOBAL_TELEPHONE: "global.telephone",
  GLOBAL_EMAIL: "global.email",
  GLOBAL_WEBSITE: "global.website",
  GLOBAL_FAX: "global.fax",
  GLOBAL_LEARN_MORE: "global.learnMore",
  GLOBAL_CLEAR_ALL: "global.clearAll",
  GLOBAL_SHOW_MORE: "global.showMore",
  GLOBAL_SITEMAP: "global.sitemap",
  GLOBAL_LOGO_LABEL: "global.logoLabel",
  GLOBAL_CLOSE: "global.close",
  GLOBAL_VIEW_MORE: "global.viewMore",
  GLOBAL_VIEW_LESS: "global.viewLess",
  GLOBAL_ADDRESS: "global.address",

  FIND_A_ROOFER_DISTANCE_LABEL: "findARoofer.distanceLabel",
  FIND_A_ROOFER_GET_DIRECTIONS_LABEL: "findARoofer.getDirectionsLabel",
  FIND_A_ROOFER_WEBSITE_LABEL: "findARoofer.websiteLabel",
  FIND_A_ROOFER_ROOF_TYPE_LABEL: "findARoofer.roofTypeLabel",
  FIND_A_ROOFER_CERTIFICATION_LABEL: "findARoofer.certificationLabel",
  FIND_A_ROOFER_NO_RESULTS_LABEL: "findARoofer.noResultsLabel",
  FIND_A_ROOFER_AND_OR: "findARoofer.andOr",
  FIND_A_ROOFER_LOCATION_FIELD_LABEL: "findARoofer.locationFieldLabel",
  FIND_A_ROOFER_GEOLOCATION_BUTTON: "findARoofer.geolocationButton",
  FIND_A_ROOFER_LIST_LABEL: "findARoofer.listLabel",
  FIND_A_ROOFER_NO_RESULTS_TITLE: "findARoofer.noResults.title",
  FIND_A_ROOFER_NO_RESULTS_SUBTITLE: "findARoofer.noResults.subtitle",
  FIND_A_ROOFER_MAP_LABEL: "findARoofer.mapLabel",

  NBA_TITLE: "nba.title",

  DOCUMENT_LIBRARY_HEADERS_PRODUCT: "documentLibrary.headers.product",
  DOCUMENT_LIBRARY_HEADERS_ALL_FILES: "documentLibrary.headers.allFiles",
  DOCUMENT_LIBRARY_HEADERS_TYPE_CODE: "documentLibrary.headers.typeCode",
  DOCUMENT_LIBRARY_HEADERS_TYPE: "documentLibrary.headers.type",
  DOCUMENT_LIBRARY_HEADERS_TITLE: "documentLibrary.headers.title",
  DOCUMENT_LIBRARY_HEADERS_DOWNLOAD: "documentLibrary.headers.download",
  DOCUMENT_LIBRARY_HEADERS_ADD: "documentLibrary.headers.add",
  DOCUMENT_LIBRARY_DOWNLOAD: "documentLibrary.download",
  DOCUMENT_LIBRARY_CARD_DOWNLOAD: "documentLibrary.card.download",
  DOCUMENT_LIBRARY_FILTERS_TITLE: "documentLibrary.filters.title",
  DOCUMENT_LIBRARY_FILTERS_CLEAR_ALL: "documentLibrary.filters.clearAll",
  DOCUMENT_LIBRARY_NO_RESULTS: "documentLibrary.noResults",

  DOCUMENTS_DOWNLOAD_MAX_REACHED: "documents.download.maxReached",

  HOMEPAGE_BRANDS: "homepage.brands",
  HOMEPAGE_BRANDS_LEARN: "homepage.brands.learn",

  CARD_COLLECTION_GROUP_TITLE: "cardCollection.groupTitle",
  CARD_COLLECTION_REST_LABEL: "cardCollection.restLabel",

  PAGE_LINK_LABEL: "page.linkLabel",
  PAGE_JUMP_TO_SECTION: "page.jumpToSection",

  DOCUMENT_DOWNLOAD_SECTION_DOCUMENT_TITLE:
    "documentDownloadSection.documentTitle",
  DOCUMENT_DOWNLOAD_SECTION_DOWNLOAD: "documentDownloadSection.download",

  DOWNLOAD_LIST_CLEAR: "downloadList.clear",
  DOWNLOAD_LIST_DOWNLOAD: "downloadList.download",
  DOWNLOAD_LIST_INFO_TITLE: "downloadList.info.title",
  DOWNLOAD_LIST_INFO_MESSAGE: "downloadList.info.message",

  PLP_FILTERS_TITLE: "plp.filters.title",
  PLP_FILTERS_CLEAR_ALL: "plp.filters.clearAll",
  PLP_PRODUCT_NO_RESULTS_FOUND: "plp.product.noResultsFound",
  PLP_PRODUCT_VIEW_DETAILS: "plp.product.viewDetails",
  PLP_PRODUCT_MORE_OPTIONS_AVAILABLE: "plp.product.moreOptionsAvailable",
  PLP_KEY_FEATURES_TITLE: "plp.keyFeatures.title",

  PDP_LEAD_BLOCK_ABOUT: "pdp.leadBlock.about",
  PDP_LEAD_BLOCK_GUARANTEES_WARRANTIES: "pdp.leadBlock.guaranteesWarranties",
  PDP_LEAD_BLOCK_AWARDS_CERTIFICATES: "pdp.leadBlock.awardsCertificates",
  PDP_LEAD_BLOCK_KEY_FEATURES: "pdp.leadBlock.keyFeatures",
  PDP_LEAD_BLOCK_TECHNICAL_SPECIFICATIONS:
    "pdp.leadBlock.technicalSpecifications",
  PDP_LEAD_BLOCK_DOCUMENTS: "pdp.leadBlock.documents",
  PDP_LEAD_BLOCK_BIM: "pdp.leadBlock.bim",
  PDP_LEAD_BLOCK_FIXING_TOOL: "pdp.leadBlock.fixingTool",
  PDP_LEAD_BLOCK_TECHNICAL_DRAWINGS: "pdp.leadBlock.technicalDrawings",
  PDP_LEAD_BLOCK_SPECIFICATION: "pdp.leadBlock.specification",
  PDP_NOBB_LABEL: "pdp.nobb.label",
  PDP_NO_TECH_SPEC_MESSAGE: "pdp.noTechSpecMessage",
  PDP_RELATED_PRODUCTS_VIEW_DETAILS: "pdp.relatedProducts.viewDetails",
  PDP_RELATED_PRODUCTS_SHOW_MORE: "pdp.relatedProducts.showMore",
  PDP_RELATED_PRODUCTS_TITLE: "pdp.relatedProducts.title",
  PDP_OVERVIEW_COMPLETE_SAMPLE_ORDER: "pdp.overview.completeSampleOrder",
  PDP_OVERVIEW_REMOVE_SAMPLE: "pdp.overview.removeSample",
  PDP_OVERVIEW_ADD_SAMPLE: "pdp.overview.addSample",
  PDP_OVERVIEW_SAMPLE_LIMIT_REACHED_MESSAGE:
    "pdp.overview.sampleLimitReachedMessage",
  PDP_OVERVIEW_CAN_ADD_MORE_MESSAGE: "pdp.overview.canAddMoreMessage",
  PDP_OVERVIEW_CAN_ADD_OTHER_MESSAGE: "pdp.overview.canAddOtherMessage",
  PDP_OVERVIEW_VARIANT_ATTRIBUTE: "pdp.overview.variantattribute",
  PDP_OVERVIEW_SIZE: "pdp.overview.size",

  SDP_SYSTEM_READ_MORE: "sdp.system.readMore",
  SDP_RECOMMENDED_SYSTEMS_TITLE: "sdp.recommendedSystemsTitle",
  SDP_LEAD_BLOCK_SPECIFICATION: "sdp.leadBlock.specification",
  SDP_LEAD_BLOCK_SYSTEM_BENEFITS: "sdp.leadBlock.systemBenefits",
  SDP_LEAD_BLOCK_BACK_TO_YOUR_SELECTION: "sdp.leadBlock.backToYourSelection",
  SDP_LEAD_BLOCK_ABOUT: "sdp.leadBlock.about",
  SDP_LEAD_BLOCK_TECHNICAL_SPECIFICATION:
    "sdp.leadBlock.technicalSpecification",
  SDP_LEAD_BLOCK_DOCUMENTS_AND_DOWNLOADS: "sdp.leadBlock.documentsAndDownloads",
  SDP_OPTIONAL_PRODUCTS_TITLE: "sdp.optionalProductsTitle",
  SDP_TABS_BIM: "sdp.tabs.bim",

  UPLOAD_FIELD_IS_REQUIRED: "upload.fieldIsRequired",
  UPLOAD_INSTRUCTIONS: "upload.instructions",
  UPLOAD_INSTRUCTIONS_DROP: "upload.instructions.drop",
  UPLOAD_INSTRUCTIONS_BROWSE: "upload.instructions.browse",

  ERRORS_EMAIL_INVALID: "errors.emailInvalid",
  ERRORS_MAX_SIZE: "errors.maxSize",

  FORM_UPLOAD_SUPPORTED_FORMATS: "form.upload.supportedFormats",
  FORM_UPLOAD_MAX_SIZE: "form.upload.maxSize",
  FORM_SUBMIT: "form.submit",

  MENU_LANGUAGE: "menu.language",
  MENU_OPEN: "menu.open",
  MENU_MAIN_TITLE: "menu.mainTitle",
  MENU_MAIN_DEFAULT: "menu.mainDefault",

  BASKET_LABEL: "basket.label",

  SEARCH_LABEL: "search.label",
  SEARCH_PLACEHOLDER_HEADER: "search.placeholder.header",
  SEARCH_PLACEHOLDER_HERO: "search.placeholder.hero",
  SEARCH_TITLE: "search.title",
  SEARCH_FILTERS_DOCUMENTS_DOCUMENT_ASSET_TYPE:
    "search.filters.documents.document-asset-type",
  SEARCH_FILTERS_PAGES_PAGE_TYPE_TAG: "search.filters.pages.page-type-tag",
  SEARCH_TAB_HEADINGS_PRODUCTS: "search.tabHeadings.products",
  SEARCH_TAB_HEADINGS_DOCUMENTS: "search.tabHeadings.documents",
  SEARCH_TAB_HEADINGS_PAGES: "search.tabHeadings.pages",

  SEARCH_PAGE_TITLE: "searchPage.title",
  SEARCH_PAGE_TITLE_WITH_QUERY: "searchPage.title.withQuery",
  SEARCH_PAGE_NO_RESULTS_TITLE: "searchPage.noResultsTitle",
  SEARCH_PAGE_SEARCH_TEXT: "searchPage.searchText",
  SEARCH_PAGE_HELPER_TEXT: "searchPage.helperText",
  SEARCH_PAGE_PLACEHOLDER: "searchPage.placeholder",

  CONFIRMATION_MESSAGE_TITLE: "confirmationMessage.title",
  CONFIRMATION_MESSAGE_BODY: "confirmationMessage.body",

  SHARE_COPY: "share.copy",
  SHARE_EMAIL: "share.email",
  SHARE_LINKEDIN: "share.linkedIn",
  SHARE_TWITTER: "share.twitter",
  SHARE_FACEBOOK: "share.facebook",
  SHARE_PINTEREST: "share.pinterest",
  SHARE_CLIPBOARD_SUCCESS: "share.clipboardSuccess",
  SHARE_CLIPBOARD_FAILURE: "share.clipboardFailure",

  GUTTERING_GUTTER_TITLE: "guttering.gutter.title",
  GUTTERING_GUTTER_VARIANT_TITLE: "guttering.gutterVariant.title",
  GUTTERING_GUTTER_HOOK_TITLE: "guttering.gutterHook.title",
  GUTTERING_DOWN_PIPE_TITLE: "guttering.downPipe.title",
  GUTTERING_DOWN_PIPE_CONNECTORS_TITLE: "guttering.downPipeConnectors.title",
  GUTTERING_TITLE: "guttering.title",
  GUTTERING_SUBTITLE: "guttering.subtitle",
  GUTTERING_NEXT_LABEL: "guttering.nextLabel",
  GUTTERING_BACK_LABEL: "guttering.backLabel",
  GUTTERING_SKIP_LABEL: "guttering.skipLabel",

  RESULTS_TABLE_TITLE: "results.table.title",
  RESULTS_TABLE_PACK_SIZE: "results.table.packSize",
  RESULTS_TABLE_EXTERNAL_PRODUCT_CODE: "results.table.externalProductCode",
  RESULTS_TABLE_QUANTITY: "results.table.quantity",
  RESULTS_TABLE_REMOVE: "results.table.remove",
  RESULTS_AREA_LABEL: "results.areaLabel",
  RESULTS_TITLE: "results.title",
  RESULTS_SUBTITLE: "results.subtitle",
  RESULTS_CATEGORIES_TILES: "results.categories.tiles",
  RESULTS_CATEGORIES_FIXINGS: "results.categories.fixings",
  RESULTS_CATEGORIES_SEALING: "results.categories.sealing",
  RESULTS_CATEGORIES_VENTELATION: "results.categories.ventilation",
  RESULTS_CATEGORIES_ACCESSORIES: "results.categories.accessories",
  RESULTS_ALERTS_QUANTITIES_TITLE: "results.alerts.quantities.title",
  RESULTS_ALERTS_QUANTITIES_TEXT: "results.alerts.quantities.text",
  RESULTS_ALERTS_NEED_TO_KNOW_TITLE: "results.alerts.needToKnow.title",
  RESULTS_ALERTS_NEED_TO_KNOW_TEXT: "results.alerts.needToKnow.text",
  RESULTS_BACK_LABEL: "results.backLabel",
  RESULTS_START_OVER_LABEL: "results.startOverLabel",
  RESULTS_DOWNLOAD_PDF_LEBEL: "results.downloadPdfLabel",
  RESULTS_EMAIL_TITLE: "results.email.title",
  RESULTS_EMAIL_HELP: "results.email.help",
  RESULTS_EMAIL_NAME_LABEL: "results.email.nameLabel",
  RESULTS_EMAIL_EMAIL_LABEL: "results.email.emailLabel",
  RESULTS_EMAIL_GDPR_1LABEL: "results.email.gdpr_1Label",
  RESULTS_EMAIL_GDPR_2LABEL: "results.email.gdpr_2Label",
  RESULTS_EMAIL_PRINT: "results.email.print",

  ROOF_SELECTION_TITLE: "roofSelection.title",
  ROOF_SELECTION_SUBTITLE: "roofSelection.subtitle",
  ROOF_SELECTION_ROOF: "roofSelection.roof",

  ROOF_DIMENSIONS_NEXT_LABEL: "roofDimensions.nextLabel",
  ROOF_DIMENSIONS_TITLE: "roofDimensions.title",
  ROOF_DIMENSIONS_SUBTITLE: "roofDimensions.subtitle",
  ROOF_DIMENSIONS_BACK_LABEL: "roofDimensions.backLabel",
  ROOF_DIMENSIONS_PROTRUSIONS_PROMT: "roofDimensions.protrusions.prompt",
  ROOF_DIMENSIONS_PROTRUSIONS_ADD_ANOTHER:
    "roofDimensions.protrusions.addAnother",
  ROOF_DIMENSIONS_PROTRUSIONS_REMOVE: "roofDimensions.protrusions.remove",
  ROOF_DIMENSIONS_PROTRUSIONS_TITLE: "roofDimensions.protrusions.title",
  ROOF_DIMENSIONS_PROTRUSIONS_ADD: "roofDimensions.protrusions.add",

  TILE_SELECTION_TITLE: "tileSelection.title",
  TILE_SELECTION_SUBTITLE: "tileSelection.subtitle",
  TILE_SELECTION_BACK_LABEL: "tileSelection.backLabel",
  TILE_SELECTION_COLOR: "tileSelection.color",
  TILE_SELECTION_COLORS: "tileSelection.colors",
  TILE_SELECTION_EMPTY: "tileSelection.empty",

  TILE_OPTIONS_TITLE: "tileOptions.title",
  TILE_OPTIONS_SUBTITLE: "tileOptions.subtitle",
  TILE_OPTIONS_NEXT_LABEL: "tileOptions.nextLabel",
  TILE_OPTIONS_BACK_LABEL: "tileOptions.backLabel",
  TILE_OPTIONS_VERGE_TITLE: "tileOptions.verge.title",
  TILE_OPTIONS_VERGE_HELP: "tileOptions.verge.help",
  TILE_OPTIONS_VERGE_NONE_LABEL: "tileOptions.verge.noneLabel",
  TILE_OPTIONS_RIDGE_TITLE: "tileOptions.ridge.title",
  TILE_OPTIONS_RIDGE_HELP: "tileOptions.ridge.help",
  TILE_OPTIONS_VENTILATION_HOOD_TITLE: "tileOptions.ventilationHood.title",
  TILE_OPTIONS_VENTILATION_HOOD_NONE_LABEL:
    "tileOptions.ventilationHood.noneLabel",

  VARIANT_SELECTION_TITLE: "variantSelection.title",
  VARIANT_SELECTION_SUBTITLE: "variantSelection.subtitle",
  VARIANT_SELECTION_BACK_LABEL: "variantSelection.backLabel",

  UNDERLAY_SELECTION_TITLE: "underlaySelection.title",
  UNDERLAY_SELECTION_SUBTITLE: "underlaySelection.subtitle",
  UNDERLAY_SELECTION_NEXT_LABEL: "underlaySelection.nextLabel",
  UNDERLAY_SELECTION_BACK_LABEL: "underlaySelection.backLabel",
  UNDERLAY_SELECTION_EMPTY: "underlaySelection.empty",

  VALIDATION_ERRORS_FIELD_REQUIRED: "validation.errors.fieldRequired",
  VALIDATION_ERRORS_EMAIL: "validation.errors.email"
};
