import type { Data as ResourceData } from "../../components/Resources";

const createResources = (resources?: Partial<ResourceData>): ResourceData => ({
  microCopy: null,
  pdpSidebarItems: null,
  pdpCardsTitle: null,
  pdpCards: null,
  pdpExploreBar: null,
  pdpShareWidget: null,
  sdpShareWidget: null,
  sdpLeadBlockCta: null,
  sdpSidebarItems: null,
  sdpBimDescription: null,
  visualiserShareWidget: null,
  pdpSignupBlock: null,
  searchPageSearchTips: null,
  searchPageSidebarItems: null,
  searchPageNextBestActions: null,
  searchPageExploreBar: null,
  errorFourOFour: null,
  errorGeneral: null,
  welcomeDialogTitle: null,
  welcomeDialogBrands: null,
  welcomeDialogBody: null,
  ieDialogTitle: null,
  ieDialogBody: null,
  ieDialogActionLabel: null,
  ieDialogActionLink: null,
  countryNavigationIntroduction: null,
  maximumSamples: null,
  sampleBasketLink: null,
  keyAssetTypes: null,
  pdpFixingToolTitle: null,
  pdpFixingToolDescription: null,
  pdpSpecificationTitle: null,
  pdpSpecificationDescription: null,
  sdpSpecificationNotesCta: null,
  documentDisplayFormat: null,
  gbbGoodIndicator: undefined,
  gbbBetterIndicator: undefined,
  gbbBestIndicator: undefined,
  ...resources
});

export default createResources;
