###

# @name search All request
POST {{esHost}}/{{productsIndex}}/_search
Content-Type: application/json
Authorization: ApiKey {{esApiKey}}

{}

###

# @name Product search request
@term=Icopal_Gruenplast-PIR_dh_23
POST {{esHost}}/{{productsIndex}}/_search
Content-Type: application/json
Authorization: ApiKey {{esApiKey}}

{
  "size": 10,
  "from": 0,
  "sort": [
    "_score",
    {
      "productScoringWeightInt": "desc"
    },
    {
      "name.keyword": "asc"
    }
  ],
  "aggs": {
    "categories": {
      "terms": {
        "size": "100",
        "field": "allCategories.code.keyword"
      }
    },
    "allCategories": {
      "terms": {
        "size": "100",
        "field": "allCategories.code.keyword"
      }
    },
    "materials": {
      "terms": {
        "size": "100",
        "field": "generalInformation.materials.code.keyword"
      }
    },
    "texturefamily": {
      "terms": {
        "size": "100",
        "field": "appearanceAttributes.texturefamily.code.keyword"
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "**",
            "type": "cross_fields",
            "fields": [
              "externalProductCode",
              "name^5",
              "summary",
              "description",
              "longDescription",
              "shortDescription",
              "appearanceAttributes.colourfamily.name.keyword",
              "generalInformation.materials.name.keyword",
              "appearanceAttributes.texturefamily.name.keyword",
              "measurementValue.keyword",
              "allCategories.value.keyword",
              "classifications.features.featureValues.value^6"
            ]
          }
        }
      ]
    }
  }
}

###

# @name Document search request
@term=BMI Icopal Profiles Brochure
POST {{esHost}}/{{documentsIndex}}/_search
Content-Type: application/json
Authorization: ApiKey {{esApiKey}}

{
  "size": 10,
  "from": 0,
  "sort": [
    {
      "assetType.name.keyword": "asc",
      "title.keyword": "asc"
    }
  ],
  "aggs": {
    "assetTypes": {
      "terms": {
        "size": "100",
        "field": "assetType.pimCode.keyword"
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "*{{term}}*",
            "type": "cross_fields",
            "fields": [
              "title"
            ]
          }
        }
      ]
    }
  }
}

###

# @name Pages search request
@term=Icopal
POST {{esHost}}/{{pagesIndex}}/_search
Content-Type: application/json
Authorization: ApiKey {{esApiKey}}

{
  "size": 10,
  "from": 0,
  "_source": {
    "excludes": [
      "pageData"
    ]
  },
  "aggs": {
    "tags": {
      "terms": {
        "size": "100",
        "field": "tags.title.keyword"
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "*{{term}}*",
            "type": "cross_fields",
            "fields": [
              "pageData"
            ]
          }
        }
      ]
    }
  }
}

###

# @name System search request
POST {{esHost}}/{{systemsIndex}}/_search
Content-Type: application/json
Authorization: ApiKey {{esApiKey}}

{}

###

# @name PLP request
@category=NO_PRODUCTS
POST {{esHost}}/{{productsIndex}}/_search
Content-Type: application/json
Authorization: ApiKey {{esApiKey}}

{
  "size": 10,
  "from": 0,
  "sort": [
    "_score",
    {
      "productScoringWeightInt": "desc"
    },
    {
      "name.keyword": "asc"
    }
  ],
  "aggs": {
    "categories": {
      "terms": {
        "size": "100",
        "field": "allCategories.code.keyword"
      }
    },
    "allCategories": {
      "terms": {
        "size": "100",
        "field": "allCategories.code.keyword"
      }
    },
    "materials": {
      "terms": {
        "size": "100",
        "field": "generalInformation.materials.code.keyword"
      }
    },
    "texturefamily": {
      "terms": {
        "size": "100",
        "field": "appearanceAttributes.texturefamily.code.keyword"
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "terms": {
            "allCategories.code.keyword": [
              "{{category}}"
            ]
          } 
        }
      ]
    }
  }
}
