###

# @name List all merge requests notes
GET https://gitlab.com/api/v4/projects/19163612/merge_requests/3664/notes?sort=asc&order_by=created_at&page=1
PRIVATE-TOKEN: {{gitlabCiPrivateToken}}

###

# @name Get specific merge request note
GET https://gitlab.com/api/v4/projects/19163612/merge_requests/3664/notes/1107702090
PRIVATE-TOKEN: {{gitlabCiPrivateToken}}
