FROM node:14-alpine

# Directory --> monorepo directory
WORKDIR /usr/src/app

# Copy workspace source files
COPY ./applications/intouch/api/db-migrations ./applications/intouch/api/db-migrations
COPY ./applications/intouch/api/services/companies/src/data ./applications/intouch/api/services/companies/src/data
COPY ./applications/intouch/api/services/training/src/data ./applications/intouch/api/services/training/src/data

WORKDIR /usr/src/app/applications/intouch/api/db-migrations

RUN yarn install

# Start
CMD [ "yarn", "start" ]
EXPOSE 8080
