FROM node:12-alpine as build

# Create apps directory
WORKDIR /usr/src/app

# Copy app files
COPY ./package.json ./package.json
COPY ./libraries ./libraries
COPY ./applications/intouch/shared ./applications/intouch/shared
COPY ./applications/intouch/api/services/companies ./applications/intouch/api/services/companies

# Install all Packages
RUN yarn install

WORKDIR /usr/src/app/applications/intouch/api/services/companies

# TypeScript
RUN yarn tsc


FROM node:12-alpine

# Create apps directory
WORKDIR /usr/src/app


# Copy app files
COPY ./package.json ./package.json
COPY ./libraries ./libraries
COPY ./applications/intouch/shared ./applications/intouch/shared
COPY ./applications/intouch/api/services/companies ./applications/intouch/api/services/companies

# Copy built files from previous stage
COPY --from=build /usr/src/app/applications/intouch/api/services/companies/dist ./applications/intouch/api/services/companies/dist

# Install prod
RUN yarn install --production --cache-folder ./ycache && \
  rm -rf ./ycache

# Create app directory
WORKDIR /usr/src/app/applications/intouch/api/services/companies

# Start
CMD [ "yarn", "start" ]
EXPOSE 8080

