FROM node:14-alpine

# Directory --> monorepo directory
WORKDIR /usr/src/app


# Copy workspace source files
COPY ./scripts ./scripts
COPY ./src/data ./src/data

WORKDIR /usr/src/app/scripts

RUN yarn install

# Start
CMD [ "yarn", "start" ]
EXPOSE 8080
