#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
yarn yalc check
yarn install --frozen-lockfile
find . -type d -name 'node_modules' -prune -false -o -type f -name 'yarn.lock' | sort | xargs sha1sum -b > modules-sha
git add modules-sha
