#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
yarn workspaces foreach run yalc check
yarn install --immutable --mode skip-build
find . -type d -name 'node_modules' -prune -false -o -type f -name 'yarn.lock' | sort | xargs sha1sum -b >modules-sha
git add modules-sha
yarn updateReferences
git add "*tsconfig.json"
