FROM node:12-alpine as build

# Create apps directory
WORKDIR /usr/src/app

# Copy app files
COPY ./package.json ./package.json
COPY ./libraries ./libraries
COPY ./applications/intouch/api/services/training ./applications/intouch/api/services/training

# Install all Packages
RUN yarn install

WORKDIR /usr/src/app/applications/intouch/api/services/training

# TypeScript
RUN yarn run build


FROM node:12-alpine

# Create apps directory
WORKDIR /usr/src/app


# Copy app files
COPY ./package.json ./package.json
COPY ./libraries ./libraries
COPY ./applications/intouch/api/services/training ./applications/intouch/api/services/training

# Copy built files from previous stage
COPY --from=build /usr/src/app/libraries/logger/dist /usr/src/app/libraries/logger/dist
COPY --from=build /usr/src/app/applications/intouch/api/services/training/dist /usr/src/app/applications/intouch/api/services/training/dist

# Install prod
RUN yarn install --production --cache-folder ./ycache && \
  rm -rf ./ycache

# Create app directory
WORKDIR /usr/src/app/applications/intouch/api/services/training

# Start
CMD [ "yarn", "start" ]
EXPOSE 8080

