import TimeAgo from "javascript-time-ago";
import en from "javascript-time-ago/locale/en";
import nb from "javascript-time-ago/locale/nb";
import it from "javascript-time-ago/locale/it";
import da from "javascript-time-ago/locale/da";
import pl from "javascript-time-ago/locale/pl";
import es from "javascript-time-ago/locale/es";
import fi from "javascript-time-ago/locale/fi";
import sv from "javascript-time-ago/locale/sv";
import pt from "javascript-time-ago/locale/pt";
import at from "javascript-time-ago/locale/de";
import nl from "javascript-time-ago/locale/nl";
import sk from "javascript-time-ago/locale/sk";
import be from "javascript-time-ago/locale/be";
import dk from "javascript-time-ago/locale/de";
import fr from "javascript-time-ago/locale/fr";
import my from "javascript-time-ago/locale/my";

TimeAgo.addDefaultLocale(en);
TimeAgo.addLocale(nb);
TimeAgo.addLocale(it);
TimeAgo.addLocale(dk);
TimeAgo.addLocale(da);
TimeAgo.addLocale(pl);
TimeAgo.addLocale(es);
TimeAgo.addLocale(fi);
TimeAgo.addLocale(sv);
TimeAgo.addLocale(pt);
TimeAgo.addLocale(at);
TimeAgo.addLocale(nl);
TimeAgo.addLocale(sk);
TimeAgo.addLocale(be);
TimeAgo.addLocale(fr);
TimeAgo.addLocale(my);
