FROM node:12-alpine as build

# Create apps directory
WORKDIR /usr/src/app

# Copy app files
COPY ./.yarn ./.yarn
COPY ./.yarnrc ./.yarnrc
COPY ./yarn.lock ./yarn.lock
COPY ./package.json ./package.json
COPY ./libraries ./libraries
COPY ./applications/intouch/api/gateway ./applications/intouch/api/gateway

# Install all Packages
# Install prod
RUN yarn install --frozen-lockfile --production --cache-folder ./ycache && \
  rm -rf ./ycache

WORKDIR /usr/src/app/applications/intouch/api/gateway

# TypeScript
RUN yarn run build


FROM node:12-alpine

# Create apps directory
WORKDIR /usr/src/app


# Copy app files
COPY ./.yarn ./.yarn
COPY ./.yarnrc ./.yarnrc
COPY ./yarn.lock ./yarn.lock
COPY ./package.json ./package.json
COPY ./libraries ./libraries
COPY ./applications/intouch/api/gateway ./applications/intouch/api/gateway

# Copy built files from previous stage
COPY --from=build /usr/src/app/libraries/logger/dist /usr/src/app/libraries/logger/dist
COPY --from=build /usr/src/app/applications/intouch/api/gateway/dist /usr/src/app/applications/intouch/api/gateway/dist


# Install prod
RUN yarn install --frozen-lockfile --production --cache-folder ./ycache && \
  rm -rf ./ycache

# Create app directory
WORKDIR /usr/src/app/applications/intouch/api/gateway

# Start
CMD [ "yarn", "start" ]
EXPOSE 8080

