FROM node:12-alpine as build

# Create apps directory
WORKDIR /usr/src/app

# Copy app files
COPY ./package.json ./package.json
COPY ./libraries ./libraries
COPY ./applications/intouch/shared ./applications/intouch/shared
COPY ./applications/intouch/api/gateway ./applications/intouch/api/gateway

# Install all Packages
RUN yarn install

WORKDIR /usr/src/app/applications/intouch/api/gateway

# TypeScript
RUN yarn tsc


FROM node:12-alpine

# Create apps directory
WORKDIR /usr/src/app


# Copy app files
COPY ./package.json ./package.json
COPY ./libraries ./libraries
COPY ./applications/intouch/shared ./applications/intouch/shared
COPY ./applications/intouch/api/gateway ./applications/intouch/api/gateway

# Copy built files from previous stage
COPY --from=build /usr/src/app/applications/intouch/api/gateway/dist ./applications/intouch/api/gateway/dist

# Install prod
RUN yarn install --production --cache-folder ./ycache && \
  rm -rf ./ycache

# Create app directory
WORKDIR /usr/src/app/applications/intouch/api/gateway

# Start
CMD [ "yarn", "start" ]
EXPOSE 8080

