FROM node:14-alpine

WORKDIR /usr/src/app
COPY ./.yarn ./.yarn
COPY ./.yarnrc ./.yarnrc
COPY ./tsconfig.json ./tsconfig.json

ARG NPM_AUTH_READ_TOKEN
COPY .npmrc .npmrc

COPY ./applications/intouch/libraries ./applications/intouch/libraries
COPY ./applications/intouch/api/types ./applications/intouch/api/types
COPY ./applications/intouch/api/gateway ./applications/intouch/api/gateway

COPY ./yarn.lock ./applications/intouch/api/gateway/yarn.lock

WORKDIR /usr/src/app/applications/intouch/api/gateway

RUN yarn install --pure-lockfile --production --cache-folder ./ycache && \
  rm -rf ./ycache

RUN rm -f ../../../../.npmrc


RUN yarn run build

CMD [ "yarn", "start" ]
